# Generated by Django 2.1.5 on 2019-02-08 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20190131_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_answer', models.IntegerField(blank=True, null=True)),
                ('option_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('txid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.Category')),
            ],
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='txid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.TransactionData'),
        ),
    ]
