# Generated by Django 2.1.5 on 2019-02-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20190208_0349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'verbose_name_plural': 'QuestionAnswers'},
        ),
        migrations.AlterModelOptions(
            name='transactiondata',
            options={'verbose_name_plural': 'TransactionData'},
        ),
    ]
