# Generated by Django 2.1.7 on 2019-03-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('categories', '0005_monzouser_squashed_0007_monzouser_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiondata',
            old_name='txid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='txid',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='categories.TransactionData'),
        ),
    ]
