# Generated by Django 2.1.7 on 2019-03-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20190325_1840_squashed_0007_auto_20190325_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='txid',
            new_name='td',
        ),
    ]
