# Generated by Django 2.1.7 on 2019-03-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20190327_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionData',
            new_name='Transaction',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
    ]
