# Generated by Django 2.1.7 on 2019-03-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20190327_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='td',
            new_name='transaction',
        ),
    ]
